fix for missing bindings in karaf extensions view
Avoid error that prevents the display of all the extensions

TypeError: Cannot read property 'extensions' of undefined
    at controllers.extension.js:16
    at Object.r [as forEach] (angular.min.js:7)
    at controllers.extension.js:14
    at angular-resource.min.js:10
    at angular.min.js:112
    at n.$eval (angular.min.js:126)
    at n.$digest (angular.min.js:123)
    at n.$apply (angular.min.js:127)
    at l (angular.min.js:81)
    at F (angular.min.js:85)

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>