MQTT embedded broker: fix missing import
Fixes: https://github.com/eclipse/smarthome/issues/6246

The error has been caused by a missing Import-Package for a javax.security
related one (see diff) that is used by Netty internally.

I tracked it down the road:

* io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
* Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId
* java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.EmptyArrays
* java.lang.NoClassDefFoundError: javax/security/cert/X509Certificate

Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>