Fixed bug 473630: handle optional dependency from rest to transform * by catching NoClassDefFoundErrors * added missing config.xml bundle to launch config
Signed-off-by: Jochen Hiller <j.hiller@telekom.de>